### ISSUE TITLE
Call CodeCarto to get parsed graph of url in href

### ISSUE THREAD

**Issue by CameronRWest** [quaternionmedia/moe#8]
**Because:**
Want to parse urls for .py raw github urls from href. 

**Done When:**
1. Clone CodeCartographer from QM 
2. Docker Compose Up in CodeCarto root dir
3. Init/Build/Run Moe
4. Go to localhost:2000
5. Click Parser
6. Input github repo that has .py files (3min load timeout)
7. Extend contents and find a .py file
8. Click PLOT
9. Click Open in Moe on new Plotter tab
10. Moe tab opens with graph of selected .py file

**Comment by subcontrabass** [comment]
Incredible!!! Works like an absolute charm
